# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('keyword1', models.CharField(max_length=30)),
                ('keyword2', models.CharField(max_length=30)),
                ('keyword3', models.CharField(max_length=30)),
                ('sentence1', models.TextField()),
                ('sentence2', models.TextField()),
                ('sentence3', models.TextField()),
            ],
        ),
    ]
