# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'Newses'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='keyword1',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='키워드1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keyword2',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='키워드2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keyword3',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='키워드3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sentence1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sentence2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sentence3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
