# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171008_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='num',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sentence1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sentence2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sentence3',
        ),
    ]
