# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171009_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
    ]
