# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171009_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='선택 키워드')),
                ('sentences1', models.TextField(blank=True, null=True, verbose_name='문장1')),
                ('sentences2', models.TextField(blank=True, null=True, verbose_name='문장2')),
                ('sentences3', models.TextField(blank=True, null=True, verbose_name='문장3')),
            ],
            options={
                'verbose_name': 'Cache',
                'verbose_name_plural': 'Caches',
            },
        ),
    ]
