# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache',
            old_name='word1',
            new_name='word',
        ),
    ]
