# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171009_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
    ]
