# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cache_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache',
            old_name='sentences1',
            new_name='sentence1',
        ),
        migrations.RenameField(
            model_name='cache',
            old_name='sentences2',
            new_name='sentence2',
        ),
        migrations.RenameField(
            model_name='cache',
            old_name='sentences3',
            new_name='sentence3',
        ),
    ]
