# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171011_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
